### PR TITLE
fix: favicon type error

### PR DESCRIPTION
**Pull request by flingyp**

### CODE REVIEW

**Comment by flingyp** [comment]
Favico attribute can be accepted three value of format. I have tested it. It shouldn't be too big a problem.
For eaxmple:
image

**Comment by viewweiwu** [comment]
Thanks for the pr, bro.

**Comment by flingyp** [comment]
Hey bro! Can you publish a version? I need to use the component. 
Thanks very much.

**Comment by flingyp** [comment]
@viewweiwu Is that OK?

**Pull request merged**
